### ISSUE TITLE
Dokumentatsiooni lisada kasutamisjuhend

### ISSUE THREAD

**Issue by niinsimo** [TTP-tark-maja/tark-maja#19]
kasutusjuhend ja/või installeerimisjuhis, kui see on vajalik (juhendi abil peab olema võimalik
"toode" peale selle koodi allalaadimist sobilikus kohas käima panna)

**Comment by liisajako** [comment]
https://docs.google.com/document/d/1EfFTlEPMdFpCHdjAYrj5f4Wg1rdk9_hZ2qS3SFBcrUs/edit?usp=sharing
